name: 'Terraform Plan Comment'
description: 'Runs terraform plan and posts the formatted output as a pull request comment with change summary'
author: 'custom-actions'

branding:
  icon: 'layers'
  color: 'purple'

inputs:
  token:
    description: 'GitHub token for posting PR comments'
    required: true
  working-directory:
    description: 'Directory containing Terraform configuration files'
    required: false
    default: '.'
  terraform-version:
    description: 'Terraform version to install and use'
    required: false
    default: '1.6'
  github-token:
    description: 'GitHub token for Terraform provider authentication (if needed)'
    required: false
    default: ''

outputs:
  plan-exitcode:
    description: 'Exit code from terraform plan (0=no changes, 2=changes present)'
    value: ${{ steps.plan.outputs.exitcode }}
  has-changes:
    description: 'Whether the plan detected infrastructure changes (true/false)'
    value: ${{ steps.plan.outputs.has-changes }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init -no-color -input=false
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || inputs.token }}

    - name: Terraform Validate
      id: validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform validate -no-color

    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e
        PLAN_OUTPUT=$(terraform plan -detailed-exitcode -no-color -input=false 2>&1)
        PLAN_EXIT_CODE=$?
        set -e

        echo "exitcode=$PLAN_EXIT_CODE" >> "$GITHUB_OUTPUT"

        # Exit code 0 = no changes, 1 = error, 2 = changes present
        if [ "$PLAN_EXIT_CODE" -eq 0 ]; then
          echo "has-changes=false" >> "$GITHUB_OUTPUT"
          echo "Plan completed: no changes detected."
        elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
          echo "has-changes=true" >> "$GITHUB_OUTPUT"
          echo "Plan completed: changes detected."
        else
          echo "has-changes=false" >> "$GITHUB_OUTPUT"
          echo "::error::Terraform plan failed with exit code $PLAN_EXIT_CODE"
        fi

        # Save plan output (truncate if too large for a PR comment)
        PLAN_LENGTH=${#PLAN_OUTPUT}
        MAX_LENGTH=60000

        if [ "$PLAN_LENGTH" -gt "$MAX_LENGTH" ]; then
          PLAN_OUTPUT="${PLAN_OUTPUT:0:$MAX_LENGTH}

        ... (output truncated, ${PLAN_LENGTH} characters total)"
        fi

        # Write to file for the comment step
        echo "$PLAN_OUTPUT" > /tmp/tf-plan-output.txt

        # Fail if there was an actual error
        if [ "$PLAN_EXIT_CODE" -eq 1 ]; then
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || inputs.token }}

    - name: Build comment body
      id: comment-body
      shell: bash
      run: |
        PLAN_EXIT_CODE="${{ steps.plan.outputs.exitcode }}"
        WORKING_DIR="${{ inputs.working-directory }}"
        PLAN_OUTPUT=$(cat /tmp/tf-plan-output.txt)

        # Determine status emoji and text
        if [ "$PLAN_EXIT_CODE" -eq 0 ]; then
          STATUS="No Changes"
          EMOJI="white_check_mark"
        elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then
          STATUS="Changes Detected"
          EMOJI="warning"
        else
          STATUS="Error"
          EMOJI="x"
        fi

        # Build the comment
        {
          echo "### :${EMOJI}: Terraform Plan - ${STATUS}"
          echo ""
          echo "**Directory:** \`${WORKING_DIR}\`"
          echo "**Terraform Version:** \`${{ inputs.terraform-version }}\`"
          echo ""
          echo "<details>"
          echo "<summary>Show Plan Output</summary>"
          echo ""
          echo '```hcl'
          echo "$PLAN_OUTPUT"
          echo '```'
          echo ""
          echo "</details>"
          echo ""
          echo "*Triggered by @${{ github.actor }} in commit \`${{ github.sha }}\`*"
        } > /tmp/tf-comment-body.txt

    - name: Post PR comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fs = require('fs');
          const { owner, repo } = context.repo;

          const prNumber = context.payload.pull_request?.number;
          if (!prNumber) {
            core.warning('Not a pull request event. Skipping comment.');
            return;
          }

          const workingDir = '${{ inputs.working-directory }}';
          const marker = `<!-- terraform-plan-comment: ${workingDir} -->`;
          const body = marker + '\n' + fs.readFileSync('/tmp/tf-comment-body.txt', 'utf8');

          // Find existing comment
          const comments = await github.paginate(
            github.rest.issues.listComments,
            { owner, repo, issue_number: prNumber, per_page: 100 }
          );

          const existing = comments.find(c => c.body && c.body.includes(marker));

          if (existing) {
            await github.rest.issues.updateComment({
              owner, repo, comment_id: existing.id, body,
            });
            core.info(`Updated comment ${existing.id}`);
          } else {
            const { data } = await github.rest.issues.createComment({
              owner, repo, issue_number: prNumber, body,
            });
            core.info(`Created comment ${data.id}`);
          }
