name: 'PR Comment'
description: 'Creates or updates a pull request comment using an upsert pattern with a hidden marker for identification'
author: 'custom-actions'

branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  token:
    description: 'GitHub token with pull-requests write permission'
    required: true
  message:
    description: 'The comment body content (supports markdown)'
    required: true
  header:
    description: 'Unique identifier string to match existing comments for upsert behavior'
    required: false
    default: ''
  pr-number:
    description: 'Pull request number. Defaults to the current PR if triggered by pull_request event'
    required: false
    default: ''

outputs:
  comment-id:
    description: 'The ID of the created or updated comment'
    value: ${{ steps.comment.outputs.comment-id }}

runs:
  using: 'composite'
  steps:
    - name: Create or update PR comment
      id: comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { owner, repo } = context.repo;
          const header = '${{ inputs.header }}';
          const message = `${{ inputs.message }}`;

          // Determine PR number
          let prNumber = '${{ inputs.pr-number }}';
          if (!prNumber && context.payload.pull_request) {
            prNumber = context.payload.pull_request.number;
          }

          if (!prNumber) {
            core.setFailed('Could not determine PR number. Provide pr-number input or run on a pull_request event.');
            return;
          }

          prNumber = parseInt(prNumber, 10);

          // Build the hidden marker for identification
          const marker = header
            ? `<!-- pr-comment-action: ${header} -->`
            : '<!-- pr-comment-action: default -->';

          const body = `${marker}\n${message}`;

          // Search for an existing comment with the marker
          let existingCommentId = null;

          const comments = await github.paginate(
            github.rest.issues.listComments,
            {
              owner,
              repo,
              issue_number: prNumber,
              per_page: 100,
            }
          );

          for (const comment of comments) {
            if (comment.body && comment.body.includes(marker)) {
              existingCommentId = comment.id;
              break;
            }
          }

          let commentId;

          if (existingCommentId) {
            // Update existing comment
            const { data } = await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: existingCommentId,
              body,
            });
            commentId = data.id;
            core.info(`Updated existing comment: ${commentId}`);
          } else {
            // Create new comment
            const { data } = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body,
            });
            commentId = data.id;
            core.info(`Created new comment: ${commentId}`);
          }

          core.setOutput('comment-id', commentId.toString());
